require('lazy').setup({
    require("plugins.lualine"),
    require("plugins.treesitter"),
    require("plugins.autopairs"),
    require("plugins.telescope"),
    require("plugins.nvim-tree"),
    require("plugins.mason"),
    require("plugins.barbar"),
    require("plugins.oxocarbon")
})
